/**
 * 디자인시스템 토큰 (tailwind.config.js 기반)
 * IIFE: window.TQ_TOKENS 로 노출. <script src="tokens.js"> 로 로드
 * @see packages/ui/config/tailwind.config.js
 */
(function () {
  "use strict";
  window.TQ_TOKENS = {
    color: {
      "semantic-primary-normal": "#ff4802",
      "semantic-primary-strong": "#e54100",
      "semantic-primary-heavy": "#cc3a00",
      "semantic-label-normal": "#171719",
      "semantic-label-strong": "#000000",
      "semantic-label-neutral": "#2e2f33e0",
      "semantic-label-alternative": "#37383c9c",
      "semantic-label-assistive": "#37383c47",
      "semantic-label-disable": "#37383c29",
      "semantic-background-normal-normal": "#ffffff",
      "semantic-background-normal-alternative": "#f7f7f8",
      "semantic-background-elevated-normal": "#ffffff",
      "semantic-background-elevated-alternative": "#f7f7f8",
      "semantic-interaction-inactive": "#989ba2",
      "semantic-interaction-disable": "#f4f4f5",
      "semantic-line-normal-normal": "#70737c38",
      "semantic-line-normal-gray": "#70737c29",
      "semantic-line-normal-alternative": "#70737c14",
      "semantic-line-normal-strong": "#70737c85",
      "semantic-line-solid-normal": "#e1e2e4",
      "semantic-line-solid-neutral": "#eaebec",
      "semantic-line-solid-alternative": "#f4f4f5",
      "semantic-line-solid-strong": "#aeb0b6",
      "semantic-fill-normal": "#70737c14",
      "semantic-fill-strong": "#70737c29",
      "semantic-fill-alternative": "#70737c0d",
      "semantic-status-positive": "#1a8038",
      "semantic-status-cautionary": "#eab305",
      "semantic-status-negative": "#da1e28",
      "semantic-status-informative": "#0f61fe",
      "semantic-static-white": "#ffffff",
      "semantic-static-black": "#000000",
      "semantic-accent-background-red-orange": "#ff4802",
      "semantic-accent-background-lime": "#58cf04",
      "semantic-accent-background-cyan": "#00bdde",
      "semantic-accent-background-light-blue": "#00aeff",
      "semantic-accent-background-violet": "#6366f1",
      "semantic-accent-background-purple": "#8a3ffc",
      "semantic-accent-background-pink": "#cf2670",
      "semantic-accent-foreground-red": "#c61b24",
      "semantic-accent-foreground-red-orange": "#f24605",
      "semantic-accent-foreground-orange": "#df6814",
      "semantic-accent-foreground-lime": "#429e00",
      "semantic-accent-foreground-green": "#187433",
      "semantic-accent-foreground-cyan": "#0098b2",
      "semantic-accent-foreground-light-blue": "#008dcf",
      "semantic-accent-foreground-blue": "#005eeb",
      "semantic-accent-foreground-violet": "#585bf2",
      "semantic-accent-foreground-purple": "#7e39e5",
      "semantic-accent-foreground-pink": "#c7216a",
      "semantic-material-dimmer": "#17171985",
      "semantic-inverse-primary": "#ff6c30",
      "semantic-inverse-background": "#1b1c1e",
      "semantic-inverse-label": "#f7f7f8",
      "atomic-cool-gray-22": "#2e2f33",
      "atomic-cool-gray-98": "#f4f4f5",
    },
    spacing: {
      3: "3px",
      4: "4px",
      5: "5px",
      6: "6px",
      7: "7px",
      8: "8px",
      9: "9px",
      11: "11px",
      12: "12px",
      14: "14px",
      16: "16px",
      20: "20px",
      28: "28px",
    },
    radius: { 6: "6px", 8: "8px", 10: "10px", 12: "12px" },
    interaction: {
      normal: { hovered: "0.05", pressed: "0.12" },
      light: { hovered: "0.0375", pressed: "0.09" },
      strong: { hovered: "0.075", pressed: "0.18" },
    },
    opacity: { 5: 0.05, 8: 0.08, 12: 0.12, 16: 0.16, 43: 0.43 },
    typography: {
      "label-one-normal-medium": {
        fontSize: "14px",
        fontWeight: 500,
        lineHeight: "142.9%",
      },
      "body-two-normal-medium": {
        fontSize: "15px",
        fontWeight: 500,
        lineHeight: "146.7%",
      },
      "caption-one-medium": {
        fontSize: "12px",
        fontWeight: 500,
        lineHeight: "133.4%",
      },
      "caption-one-normal-medium": {
        fontSize: "12px",
        fontWeight: 500,
        lineHeight: "133.4%",
      },
      "label-two-bold": {
        fontSize: "13px",
        fontWeight: 600,
        lineHeight: "138.5%",
      },
      "body-two-normal-bold": {
        fontSize: "15px",
        fontWeight: 600,
        lineHeight: "146.7%",
      },
      "body-one-normal-bold": {
        fontSize: "16px",
        fontWeight: 600,
        lineHeight: "150%",
      },
      "label-one-normal-bold": {
        fontSize: "14px",
        fontWeight: 600,
        lineHeight: "142.9%",
      },
      "caption-two-medium": {
        fontSize: "11px",
        fontWeight: 500,
        lineHeight: "127.3%",
      },
      "caption-two-bold": {
        fontSize: "11px",
        fontWeight: 600,
        lineHeight: "127.3%",
      },
      "label-two-medium": {
        fontSize: "13px",
        fontWeight: 500,
        lineHeight: "138.5%",
      },
      "label-two-regular": {
        fontSize: "13px",
        fontWeight: 400,
        lineHeight: "138.5%",
      },
    },
  };
})();
